### ISSUE TITLE
Events preventDefault

### ISSUE THREAD

**Issue by MahmodMhamed** [WebAhead8/TDD-ToDoDo-List#9]
There are some lines:
```javaScript
 event.preventDefault():
```

You should use it only if you want to prevent something - for example:
1. Check box/radio button - if you use preventDefault it will not be checked.
2. href - preventDefault will not open the link.
3. form - preventDefault will not go to action url (redirecting).

if there is no something special that you want to prevent, there is no meaning for it.

**Comment by haneenawad** [comment]
done
